#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -f /config/config.yaml ]; then
    # write_info "Creating default config.yaml"
    echo "Setting up sample config.yaml"
    cp -u /defaults/config/config.yaml.sample /config/config.yaml.sample
fi
