version: 1
disable_existing_loggers: True

formatters:
  standard_formatter:
    class: coloredlogs.ColoredFormatter
    format: "%(asctime)s [%(levelname)8s] : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  standard_detailed_formatter:
    format: "%(asctime)s|%(levelname)8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  extended_formatter:
    class: coloredlogs.ColoredFormatter
    format: "%(asctime)s [%(levelname)8s] %(name)s.%(funcName)s(%(lineno)s) : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  extended_detailed_formatter:
    format: "%(asctime)s|%(name)s|%(levelname)s|<PID %(process)d:%(processName)s>|%(name)s.%(funcName)s(%(lineno)s)|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  standard_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard_detailed_formatter
    filename: traefik-certificate-exporter.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  extended_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: extended_detailed_formatter
    filename: traefik-certificate-exporter.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  standard_console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: standard_formatter
    stream: ext://sys.stdout

  extended_console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: extended_formatter
    stream: ext://sys.stdout

loggers:
  traefik_certificate_exporter_consoleonly:
    handlers: [standard_console_handler]
    level: INFO
    propagate: False

  traefik_certificate_exporter:
    handlers: [standard_console_handler, extended_file_handler]
    level: INFO
    propagate: False

root:
    level: ERROR
    handlers: [standard_console_handler] 
    propagate: False

