#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["tomlkit>=0.13", "ruamel.yaml>=0.18"]
# ///
"""
write-module-config.py — record an l3io module's project-level settings in the
BMad central config.

Why this exists
---------------
BMad 6.10 resolves central config from four TOML layers, merged in order:

  1. {project-root}/_bmad/config.toml              installer-owned, team-scoped
  2. {project-root}/_bmad/config.user.toml         installer-owned, user-scoped
  3. {project-root}/_bmad/custom/config.toml       human-authored, committed
  4. {project-root}/_bmad/custom/config.user.toml  human-authored, gitignored

Layers 1-2 are regenerated by the installer on every install — anything written
there is lost. Layers 3-4 are never touched by the installer, so they are the
only correct destination for settings a skill collects. This script writes to
layers 3-4 and nothing else.

Module settings live under `[modules.<code>]`, matching how BMad core reads them
(e.g. bmad-help reads `modules.bmm.project_knowledge`). Values marked
`user_setting: true` in module.yaml go to the `.user.toml` layer instead, so a
personal preference never lands in a committed file.

Anti-zombie: the module's own table is replaced wholesale rather than merged, so
a key removed from module.yaml cannot survive as a stale entry. Other modules'
tables and all surrounding comments are preserved (tomlkit round-trip).

Usage
-----
  uv run write-module-config.py \
      --project-root /abs/path/to/project \
      --module-yaml  /abs/path/to/module.yaml \
      --answers      /tmp/answers.json

  # no collected settings — just report what registration would mean
  uv run write-module-config.py --project-root ... --module-yaml ... --dry-run

The answers file is JSON: {"module": {"key": "value", ...}}. Keys not declared
in module.yaml's `variables:` are rejected, so a typo fails loudly instead of
writing a setting nothing reads.

Prints a JSON result to stdout: files written, per-layer keys, and whether this
was a fresh registration or an update. Errors go to stderr with a nonzero exit.
"""

import argparse
import json
import sys
from pathlib import Path

try:
    import tomlkit
except ImportError:  # pragma: no cover - dependency provisioned by uv
    sys.stderr.write(
        "error: tomlkit is required. Run this script with `uv run` so the "
        "PEP-723 header provisions it, or `pip install tomlkit`.\n"
    )
    sys.exit(3)

try:
    from ruamel.yaml import YAML
except ImportError:  # pragma: no cover - dependency provisioned by uv
    sys.stderr.write(
        "error: ruamel.yaml is required. Run this script with `uv run` so the "
        "PEP-723 header provisions it, or `pip install ruamel.yaml`.\n"
    )
    sys.exit(3)


TEAM_LAYER = ("custom", "config.toml")
USER_LAYER = ("custom", "config.user.toml")

TEAM_HEADER = """\
# Team / enterprise overrides for _bmad/config.toml.
# Committed to the repo — applies to every developer on the project.
# Tables deep-merge over base config; keyed entries merge by key.
"""

USER_HEADER = """\
# Personal overrides for _bmad/config.toml.
# NOT committed (gitignored) — applies only to your local install.
# Wins over both base config and team overrides.
"""


def fail(message: str, code: int = 1) -> None:
    sys.stderr.write(f"error: {message}\n")
    sys.exit(code)


def load_module_yaml(path: Path) -> dict:
    if not path.exists():
        fail(f"module.yaml not found: {path}")
    yaml = YAML(typ="safe")
    try:
        with path.open("r", encoding="utf-8") as handle:
            data = yaml.load(handle)
    except Exception as error:  # noqa: BLE001 - surface any parse failure verbatim
        fail(f"failed to parse {path}: {error}")
    if not isinstance(data, dict):
        fail(f"{path} did not parse to a mapping")
    if not data.get("code"):
        fail(f"{path} has no `code:` field — cannot identify the module")
    return data


def declared_variables(module: dict) -> dict:
    """Map variable name -> True when the variable is user-scoped."""
    variables = module.get("variables") or []
    if isinstance(variables, dict):
        # Mapping form: {name: {user_setting: bool, ...}}
        return {
            str(name): bool((spec or {}).get("user_setting", False))
            for name, spec in variables.items()
        }
    scoped = {}
    for entry in variables:
        if not isinstance(entry, dict):
            continue
        name = entry.get("name")
        if not name:
            continue
        scoped[str(name)] = bool(entry.get("user_setting", False))
    return scoped


def load_answers(path: Path | None) -> dict:
    if path is None:
        return {}
    if not path.exists():
        fail(f"answers file not found: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        fail(f"failed to parse {path}: {error}")
    if not isinstance(payload, dict):
        fail(f"{path} must contain a JSON object")
    module_values = payload.get("module", {})
    if not isinstance(module_values, dict):
        fail(f"{path}: `module` must be a JSON object")
    return module_values


def split_by_scope(values: dict, scoped: dict, module_code: str) -> tuple[dict, dict]:
    unknown = sorted(set(values) - set(scoped))
    if unknown:
        fail(
            f"module.yaml for `{module_code}` does not declare: {', '.join(unknown)}. "
            "Add them under `variables:` or drop them from the answers file."
        )
    team = {k: v for k, v in values.items() if not scoped[k]}
    user = {k: v for k, v in values.items() if scoped[k]}
    return team, user


def read_doc(path: Path, header: str):
    if path.exists():
        try:
            return tomlkit.parse(path.read_text(encoding="utf-8"))
        except Exception as error:  # noqa: BLE001
            fail(f"failed to parse {path}: {error}")
    doc = tomlkit.parse(header)
    return doc


def write_module_table(path: Path, header: str, module_code: str, values: dict) -> str:
    """Replace [modules.<code>] in `path`. Returns 'created' or 'updated'."""
    existed = path.exists()
    doc = read_doc(path, header)

    modules = doc.get("modules")
    if modules is None:
        modules = tomlkit.table(is_super_table=True)
        doc["modules"] = modules

    was_registered = module_code in modules

    table = tomlkit.table()
    for key, value in values.items():
        table[key] = value
    # Anti-zombie: assignment replaces the whole table, so keys dropped from
    # module.yaml cannot linger.
    modules[module_code] = table

    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(tomlkit.dumps(doc), encoding="utf-8")
    tmp.replace(path)

    if not existed:
        return "created"
    return "updated" if was_registered else "registered"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Write an l3io module's settings into the human-authored BMad config "
            "layers (_bmad/custom/config.toml and config.user.toml)."
        )
    )
    parser.add_argument(
        "--project-root",
        required=True,
        help="Absolute path to the project root (the directory containing _bmad/)",
    )
    parser.add_argument(
        "--module-yaml",
        required=True,
        help="Path to the calling skill's module.yaml (supplies `code` and `variables`)",
    )
    parser.add_argument(
        "--answers",
        help='JSON file of collected values: {"module": {"key": "value"}}',
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would be written without touching any file",
    )
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    bmad_dir = project_root / "_bmad"
    if not bmad_dir.is_dir():
        fail(
            f"{bmad_dir} not found — BMad is not installed in this project. "
            "Run the BMad installer before configuring a module."
        )

    module = load_module_yaml(Path(args.module_yaml))
    module_code = str(module["code"])
    scoped = declared_variables(module)

    values = load_answers(Path(args.answers) if args.answers else None)
    team_values, user_values = split_by_scope(values, scoped, module_code)

    result = {
        "module": module_code,
        "module_version": module.get("module_version"),
        "team": {"path": None, "keys": sorted(team_values), "status": "unchanged"},
        "user": {"path": None, "keys": sorted(user_values), "status": "unchanged"},
        "dry_run": bool(args.dry_run),
    }

    for bucket, layer, header, bucket_values in (
        ("team", TEAM_LAYER, TEAM_HEADER, team_values),
        ("user", USER_LAYER, USER_HEADER, user_values),
    ):
        if not bucket_values:
            continue
        path = bmad_dir.joinpath(*layer)
        result[bucket]["path"] = str(path)
        if args.dry_run:
            result[bucket]["status"] = "would-write"
            continue
        result[bucket]["status"] = write_module_table(
            path, header, module_code, bucket_values
        )

    if not values:
        result["note"] = (
            f"`{module_code}` declares no project-level settings — nothing to write. "
            "The module is usable as installed; skills resolve defaults at activation."
        )

    json.dump(result, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
