name: Build and publish python package

on:
  workflow_call:
  release:
    types: [ published ]

permissions:
    contents: write

env:
    PACKAGE_REPO: ${{ vars.PACKAGE_REPO || 'testpypi' }}
    GITHUB_TAG: ${{ vars.RELEASE_GITHUB_TAG || '' }}
    PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.11' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository # You must checkout your repository first.
        uses: actions/checkout@v7

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Publish PyPi package
        uses: cadifyai/poetry-publish@v0.1.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
          PUBLISH_REGISTRY: ${{ env.PACKAGE_REPO }}
          PUBLISH_REGISTRY_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
