name: build-all

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-package:
    uses: ./.github/workflows/build-package.yaml
    secrets: inherit

  build-container:
    uses: ./.github/workflows/build-container.yaml
    secrets: inherit
